/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tubespbo.program;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Abdul Hakim
 */
public class HalamanApotek extends javax.swing.JFrame {

    
    private void kosongkan_form(){
        txtkode_obat.setEditable(true);
        txtkode_obat.setText(null);
        txtsuppliers_id.setText(null);
        txtnama_obat.setText(null);
        txtprodusen.setText(null);
        txtstok.setText(null);
        txtharga.setText(null);   
    }
       
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Kode Obat");
        model.addColumn("Suppliers Id");
        model.addColumn("Nama Obat");
        model.addColumn("Produsen");
        model.addColumn("Stok");
        model.addColumn("Harga");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM obat";
            java.sql.Connection conn=(Connection)home.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next ()){
                model.addRow(new Object []{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});          
            }
            tableobat.setModel(model);
            
        }catch (SQLException e){
            System.out.println("error : " + e.getMessage());     
        }
    }
       
    /**
     * Creates new form HalamanApotek
     */
    public HalamanApotek() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtkode_obat = new javax.swing.JTextField();
        txtsuppliers_id = new javax.swing.JTextField();
        txtnama_obat = new javax.swing.JTextField();
        txtprodusen = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        btreset = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableobat = new javax.swing.JTable();
        BarPanel = new javax.swing.JPanel();
        bthome = new javax.swing.JButton();
        btuser = new javax.swing.JButton();
        btpencarian = new javax.swing.JButton();
        btobat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Apotek Rose Gold");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 24, 91));
        jPanel2.setForeground(new java.awt.Color(247, 117, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Obat");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 30, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Suppliers ID");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 70, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Produsen");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 150, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Obat");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 110, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stok");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 190, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 230, 100, 30);

        txtkode_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtkode_obat);
        txtkode_obat.setBounds(140, 30, 200, 30);

        txtsuppliers_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtsuppliers_id);
        txtsuppliers_id.setBounds(140, 70, 200, 30);

        txtnama_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtnama_obat);
        txtnama_obat.setBounds(140, 110, 200, 30);

        txtprodusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprodusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodusenActionPerformed(evt);
            }
        });
        jPanel2.add(txtprodusen);
        txtprodusen.setBounds(140, 150, 200, 30);

        txtstok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtstok);
        txtstok.setBounds(140, 190, 200, 30);

        txtharga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtharga);
        txtharga.setBounds(140, 230, 200, 30);

        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });
        jPanel2.add(btreset);
        btreset.setBounds(80, 290, 80, 30);

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btkeluar);
        btkeluar.setBounds(260, 340, 80, 30);

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel2.add(bthapus);
        bthapus.setBounds(80, 340, 80, 30);

        btsimpan.setText("Simpan");
        btsimpan.setPreferredSize(new java.awt.Dimension(63, 23));
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btsimpan);
        btsimpan.setBounds(260, 290, 80, 30);

        btedit.setText("Edit");
        btedit.setPreferredSize(new java.awt.Dimension(63, 23));
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        jPanel2.add(btedit);
        btedit.setBounds(180, 290, 60, 30);

        btbatal.setText("Batal");
        btbatal.setMaximumSize(new java.awt.Dimension(51, 23));
        btbatal.setMinimumSize(new java.awt.Dimension(51, 23));
        btbatal.setPreferredSize(new java.awt.Dimension(63, 23));
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        jPanel2.add(btbatal);
        btbatal.setBounds(180, 340, 60, 30);

        tableobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableobatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableobat);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(370, 30, 640, 270);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 1040, 440));

        BarPanel.setBackground(new java.awt.Color(194, 24, 91));
        BarPanel.setLayout(null);

        bthome.setBackground(new java.awt.Color(194, 24, 91));
        bthome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bthome.setForeground(new java.awt.Color(255, 255, 255));
        bthome.setText("Home");
        bthome.setContentAreaFilled(false);
        bthome.setOpaque(true);
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });
        BarPanel.add(bthome);
        bthome.setBounds(0, 0, 73, 40);

        btuser.setBackground(new java.awt.Color(194, 24, 91));
        btuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btuser.setForeground(new java.awt.Color(255, 255, 255));
        btuser.setText("User");
        btuser.setContentAreaFilled(false);
        btuser.setOpaque(true);
        btuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuserActionPerformed(evt);
            }
        });
        BarPanel.add(btuser);
        btuser.setBounds(140, 0, 63, 40);

        btpencarian.setBackground(new java.awt.Color(194, 24, 91));
        btpencarian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpencarian.setForeground(new java.awt.Color(255, 255, 255));
        btpencarian.setText("Search");
        btpencarian.setContentAreaFilled(false);
        btpencarian.setOpaque(true);
        btpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpencarianActionPerformed(evt);
            }
        });
        BarPanel.add(btpencarian);
        btpencarian.setBounds(70, 0, 79, 40);

        btobat.setBackground(new java.awt.Color(194, 24, 91));
        btobat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btobat.setForeground(new java.awt.Color(255, 255, 255));
        btobat.setText("Data Obat");
        btobat.setContentAreaFilled(false);
        btobat.setOpaque(true);
        btobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btobatActionPerformed(evt);
            }
        });
        BarPanel.add(btobat);
        btobat.setBounds(190, 0, 103, 40);

        getContentPane().add(BarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1040, 40));

        jPanel1.setBackground(new java.awt.Color(194, 24, 91));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(45, 20, 44));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Obat Apotek Rose Gold");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1040, 60));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/OBackground 2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtprodusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodusenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodusenActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM obat WHERE kode_obat ='"+txtkode_obat.getText()+"'";
            java.sql.Connection conn = (Connection)home.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_bthapusActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO obat VALUES ('"+txtkode_obat.getText()+"','"+txtsuppliers_id.getText()+"','"+txtnama_obat.getText()+"','"+txtprodusen.getText()+"','"+txtstok.getText()+"','"+txtharga.getText()+"')";
            java.sql.Connection conn = (Connection)home.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil");
            tampilkan_data();
            kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE obat SET kode_obat ='"+txtkode_obat.getText()+"',supplier_id='"+txtsuppliers_id.getText()+"',nama_obat='"+txtnama_obat.getText()+"',produsen='"+txtprodusen.getText()+"',stok='"+txtstok.getText()+"',harga='"+txtharga.getText()+"' WHERE kode_obat= '"+txtkode_obat.getText()+"'";
            java.sql.Connection conn = (Connection)home.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_bteditActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btbatalActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btresetActionPerformed

    private void tableobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableobatMouseClicked
        // TODO add your handling code here:
        int baris = tableobat.rowAtPoint(evt.getPoint());
        String kode_obat = tableobat.getValueAt(baris, 1).toString();
        txtkode_obat.setText(kode_obat);

        String suppliers_id = tableobat.getValueAt(baris, 2).toString();
        txtsuppliers_id.setText(suppliers_id);

        String nama_obat = tableobat.getValueAt(baris, 3).toString();
        txtnama_obat.setText(nama_obat);

        String produsen = tableobat.getValueAt(baris, 4).toString();
        txtprodusen.setText(produsen);

        String stok = tableobat.getValueAt(baris, 5).toString();
        txtstok.setText(stok);

        String harga = tableobat.getValueAt(baris, 6).toString();
        txtharga.setText(harga);
    }//GEN-LAST:event_tableobatMouseClicked

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanAwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthomeActionPerformed

    private void btuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btuserActionPerformed

    private void btpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpencarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSearch().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpencarianActionPerformed

    private void btobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btobatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanApotek().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btobatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanApotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel BarPanel;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bthome;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btobat;
    private javax.swing.JButton btpencarian;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableobat;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode_obat;
    private javax.swing.JTextField txtnama_obat;
    private javax.swing.JTextField txtprodusen;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txtsuppliers_id;
    // End of variables declaration//GEN-END:variables
}
