/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tubespbo.program;

/**
 *
 * @author Muhammad Abdul Hakim
 */
public class AboutUS extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAwal
     */
    public AboutUS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        BarPanel = new javax.swing.JPanel();
        bthome1 = new javax.swing.JButton();
        btAS1 = new javax.swing.JButton();
        btLogin1 = new javax.swing.JButton();
        btpencarian1 = new javax.swing.JButton();
        bthelp1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JAboutUS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        closeX = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel.setLayout(null);

        BarPanel.setBackground(new java.awt.Color(194, 24, 91));
        BarPanel.setLayout(null);

        bthome1.setBackground(new java.awt.Color(194, 24, 91));
        bthome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bthome1.setForeground(new java.awt.Color(255, 255, 255));
        bthome1.setText("Home");
        bthome1.setContentAreaFilled(false);
        bthome1.setOpaque(true);
        bthome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthome1ActionPerformed(evt);
            }
        });
        BarPanel.add(bthome1);
        bthome1.setBounds(0, 0, 73, 50);

        btAS1.setBackground(new java.awt.Color(194, 24, 91));
        btAS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAS1.setForeground(new java.awt.Color(255, 255, 255));
        btAS1.setText("About US");
        btAS1.setContentAreaFilled(false);
        btAS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAS1.setOpaque(true);
        btAS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAS1ActionPerformed(evt);
            }
        });
        BarPanel.add(btAS1);
        btAS1.setBounds(190, 0, 100, 50);

        btLogin1.setBackground(new java.awt.Color(194, 24, 91));
        btLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btLogin1.setText("Login");
        btLogin1.setContentAreaFilled(false);
        btLogin1.setOpaque(true);
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });
        BarPanel.add(btLogin1);
        btLogin1.setBounds(60, 0, 71, 50);

        btpencarian1.setBackground(new java.awt.Color(194, 24, 91));
        btpencarian1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpencarian1.setForeground(new java.awt.Color(255, 255, 255));
        btpencarian1.setText("Search");
        btpencarian1.setContentAreaFilled(false);
        btpencarian1.setOpaque(true);
        btpencarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpencarian1ActionPerformed(evt);
            }
        });
        BarPanel.add(btpencarian1);
        btpencarian1.setBounds(120, 0, 79, 50);

        bthelp1.setBackground(new java.awt.Color(194, 24, 91));
        bthelp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bthelp1.setForeground(new java.awt.Color(255, 255, 255));
        bthelp1.setText("Help");
        bthelp1.setContentAreaFilled(false);
        bthelp1.setOpaque(true);
        bthelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthelp1ActionPerformed(evt);
            }
        });
        BarPanel.add(bthelp1);
        bthelp1.setBounds(280, 0, 63, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APOTEK ROSEGOLD");
        BarPanel.add(jLabel3);
        jLabel3.setBounds(770, 0, 190, 50);

        BackgroundPanel.add(BarPanel);
        BarPanel.setBounds(20, 20, 970, 50);

        JAboutUS.setBackground(new java.awt.Color(255, 255, 255));
        JAboutUS.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("118140183");
        JAboutUS.add(jLabel6);
        jLabel6.setBounds(210, 300, 150, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Muhammad Abdul Hakim");
        JAboutUS.add(jLabel7);
        jLabel7.setBounds(210, 280, 160, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Annisa Jufe Aryani");
        JAboutUS.add(jLabel8);
        jLabel8.setBounds(60, 280, 130, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("118140124");
        JAboutUS.add(jLabel9);
        jLabel9.setBounds(60, 300, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Febby Sartika");
        JAboutUS.add(jLabel10);
        jLabel10.setBounds(410, 280, 100, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("118140137");
        JAboutUS.add(jLabel11);
        jLabel11.setBounds(410, 300, 80, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Aplikasi Sistem Informasi Apotek ");
        JAboutUS.add(jLabel12);
        jLabel12.setBounds(0, 20, 550, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Aplikasi yang bertema Sistem Informasi Apotek ini dibuat untuk memenuhi");
        JAboutUS.add(jLabel13);
        jLabel13.setBounds(0, 80, 550, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("tugas besar dari mata kuliah Pemrograman Berorientasi Objek IF2222");
        JAboutUS.add(jLabel14);
        jLabel14.setBounds(0, 100, 550, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/Jufe.jpeg"))); // NOI18N
        JAboutUS.add(jLabel4);
        jLabel4.setBounds(50, 150, 130, 130);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/Febby.jpeg"))); // NOI18N
        jLabel15.setText("jLabel3");
        JAboutUS.add(jLabel15);
        jLabel15.setBounds(380, 150, 130, 130);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/Hakim.jpeg"))); // NOI18N
        jLabel16.setText("jLabel3");
        JAboutUS.add(jLabel16);
        jLabel16.setBounds(220, 150, 130, 130);

        closeX.setBackground(new java.awt.Color(255, 255, 255));
        closeX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeX.setText("X");
        closeX.setContentAreaFilled(false);
        closeX.setOpaque(true);
        closeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeXActionPerformed(evt);
            }
        });
        JAboutUS.add(closeX);
        closeX.setBounds(503, 0, 50, 30);

        BackgroundPanel.add(JAboutUS);
        JAboutUS.setBounds(220, 110, 550, 390);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/OBackground 2.jpg"))); // NOI18N
        Background.setText("jLabel1");
        BackgroundPanel.add(Background);
        Background.setBounds(-80, 0, 1090, 550);

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bthome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthome1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanAwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthome1ActionPerformed

    private void btAS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAS1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AboutUS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAS1ActionPerformed

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogin1ActionPerformed

    private void btpencarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpencarian1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSearch().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpencarian1ActionPerformed

    private void bthelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthelp1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthelp1ActionPerformed

    private void closeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeXActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanAwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BarPanel;
    private javax.swing.JPanel JAboutUS;
    private javax.swing.JButton btAS1;
    private javax.swing.JButton btLogin1;
    private javax.swing.JButton bthelp1;
    private javax.swing.JButton bthome1;
    private javax.swing.JButton btpencarian1;
    private javax.swing.JButton closeX;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
