/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tubespbo.program;

import java.sql.*;
import javax.swing.*;
import com.tubespbo.program.koneksi;



/**
 *
 * @author Muhammad Abdul Hakim
 */
public class HalamanLogin extends javax.swing.JFrame {
    Connection conn = koneksi.getkoneksi();
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form HalamanLogin
     */
    public HalamanLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        BarPanel = new javax.swing.JPanel();
        bthome = new javax.swing.JButton();
        btAS = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();
        btpencarian = new javax.swing.JButton();
        bthelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        txpassword = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarPanel.setBackground(new java.awt.Color(194, 24, 91));
        BarPanel.setLayout(null);

        bthome.setBackground(new java.awt.Color(194, 24, 91));
        bthome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bthome.setForeground(new java.awt.Color(255, 255, 255));
        bthome.setText("Home");
        bthome.setContentAreaFilled(false);
        bthome.setOpaque(true);
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });
        BarPanel.add(bthome);
        bthome.setBounds(0, 0, 73, 50);

        btAS.setBackground(new java.awt.Color(194, 24, 91));
        btAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAS.setForeground(new java.awt.Color(255, 255, 255));
        btAS.setText("About US");
        btAS.setContentAreaFilled(false);
        btAS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAS.setOpaque(true);
        btAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btASActionPerformed(evt);
            }
        });
        BarPanel.add(btAS);
        btAS.setBounds(190, 0, 100, 50);

        btLogin.setBackground(new java.awt.Color(194, 24, 91));
        btLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.setContentAreaFilled(false);
        btLogin.setOpaque(true);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        BarPanel.add(btLogin);
        btLogin.setBounds(60, 0, 71, 50);

        btpencarian.setBackground(new java.awt.Color(194, 24, 91));
        btpencarian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpencarian.setForeground(new java.awt.Color(255, 255, 255));
        btpencarian.setText("Search");
        btpencarian.setContentAreaFilled(false);
        btpencarian.setOpaque(true);
        btpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpencarianActionPerformed(evt);
            }
        });
        BarPanel.add(btpencarian);
        btpencarian.setBounds(120, 0, 79, 50);

        bthelp.setBackground(new java.awt.Color(194, 24, 91));
        bthelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bthelp.setForeground(new java.awt.Color(255, 255, 255));
        bthelp.setText("Help");
        bthelp.setContentAreaFilled(false);
        bthelp.setOpaque(true);
        bthelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthelpActionPerformed(evt);
            }
        });
        BarPanel.add(bthelp);
        bthelp.setBounds(280, 0, 63, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APOTEK ROSEGOLD");
        BarPanel.add(jLabel2);
        jLabel2.setBounds(770, 0, 190, 50);

        BackgroundPanel.add(BarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 970, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(194, 24, 91));
        jPanel4.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(205, 142, 151));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SELAMAT DATANG");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 20, 320, 34);

        jPanel2.setBackground(new java.awt.Color(194, 24, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(183, 107, 120));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txnama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnamaActionPerformed(evt);
            }
        });
        jPanel2.add(txnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, -1));

        txpassword.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, -1));

        login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(194, 24, 91));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jPanel4.add(jPanel2);
        jPanel2.setBounds(50, 110, 240, 210);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Masukan username dan password Anda.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 90, 230, 20);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 330, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/OBackground 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 610, 410));

        BackgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 910, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/OBackground 2.jpg"))); // NOI18N
        BackgroundPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    private void txpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpasswordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String sql = "select * from admin where username=? and password=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txnama.getText());
            pst.setString(2, String.valueOf(txpassword.getPassword()));
            rs=pst.executeQuery();
            if(rs.next()){
                this.setVisible(false);
                new HalamanApotek().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Upss Gagagl, Username/Password Salah!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void bthelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthelpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthelpActionPerformed

    private void btpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpencarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSearch().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpencarianActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btASActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AboutUS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btASActionPerformed

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanAwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BarPanel;
    private javax.swing.JButton btAS;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton bthelp;
    private javax.swing.JButton bthome;
    private javax.swing.JButton btpencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login;
    private javax.swing.JTextField txnama;
    private javax.swing.JPasswordField txpassword;
    // End of variables declaration//GEN-END:variables
}
