/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tubespbo.program;

/**
 *
 * @author Muhammad Abdul Hakim
 */
public class HalamanAwal extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAwal
     */
    public HalamanAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        BarPanel = new javax.swing.JPanel();
        bthome1 = new javax.swing.JButton();
        btLogin1 = new javax.swing.JButton();
        btpencarian1 = new javax.swing.JButton();
        btAboutUS = new javax.swing.JButton();
        bthelp1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel.setLayout(null);

        BarPanel.setBackground(new java.awt.Color(194, 24, 91));
        BarPanel.setLayout(null);

        bthome1.setBackground(new java.awt.Color(194, 24, 91));
        bthome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bthome1.setForeground(new java.awt.Color(255, 255, 255));
        bthome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/baseline_home_white_18dp.png"))); // NOI18N
        bthome1.setText("Home");
        bthome1.setContentAreaFilled(false);
        bthome1.setOpaque(true);
        bthome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthome1ActionPerformed(evt);
            }
        });
        BarPanel.add(bthome1);
        bthome1.setBounds(70, 130, 130, 50);

        btLogin1.setBackground(new java.awt.Color(194, 24, 91));
        btLogin1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/baseline_input_white_18dp.png"))); // NOI18N
        btLogin1.setText("Login");
        btLogin1.setContentAreaFilled(false);
        btLogin1.setOpaque(true);
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });
        BarPanel.add(btLogin1);
        btLogin1.setBounds(70, 190, 130, 50);

        btpencarian1.setBackground(new java.awt.Color(194, 24, 91));
        btpencarian1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btpencarian1.setForeground(new java.awt.Color(255, 255, 255));
        btpencarian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/baseline_search_white_18dp.png"))); // NOI18N
        btpencarian1.setText("Search");
        btpencarian1.setContentAreaFilled(false);
        btpencarian1.setOpaque(true);
        btpencarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpencarian1ActionPerformed(evt);
            }
        });
        BarPanel.add(btpencarian1);
        btpencarian1.setBounds(70, 250, 130, 50);

        btAboutUS.setBackground(new java.awt.Color(194, 24, 91));
        btAboutUS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAboutUS.setForeground(new java.awt.Color(255, 255, 255));
        btAboutUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/baseline_info_white_18dp.png"))); // NOI18N
        btAboutUS.setText("About Us");
        btAboutUS.setContentAreaFilled(false);
        btAboutUS.setOpaque(true);
        btAboutUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutUSActionPerformed(evt);
            }
        });
        BarPanel.add(btAboutUS);
        btAboutUS.setBounds(70, 310, 129, 50);

        bthelp1.setBackground(new java.awt.Color(194, 24, 91));
        bthelp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bthelp1.setForeground(new java.awt.Color(255, 255, 255));
        bthelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/baseline_help_white_18dp.png"))); // NOI18N
        bthelp1.setText("Help");
        bthelp1.setContentAreaFilled(false);
        bthelp1.setOpaque(true);
        bthelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthelp1ActionPerformed(evt);
            }
        });
        BarPanel.add(bthelp1);
        bthelp1.setBounds(70, 370, 130, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(194, 24, 91));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jl. Tugas Besar No. 20, Kota Buntu, Wevwoodl");
        BarPanel.add(jLabel4);
        jLabel4.setBounds(0, 80, 480, 13);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 24, 91));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APOTEK ROSEGOLD");
        BarPanel.add(jLabel3);
        jLabel3.setBounds(0, 30, 480, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/Putihh.jpg"))); // NOI18N
        BarPanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 870, 450);

        BackgroundPanel.add(BarPanel);
        BarPanel.setBounds(70, 50, 870, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/jpg/OBackground 2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        BackgroundPanel.add(jLabel1);
        jLabel1.setBounds(-80, 0, 1090, 550);

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bthome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthome1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanAwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthome1ActionPerformed

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogin1ActionPerformed

    private void btpencarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpencarian1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSearch().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpencarian1ActionPerformed

    private void bthelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthelp1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthelp1ActionPerformed

    private void btAboutUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutUSActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AboutUS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAboutUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BarPanel;
    private javax.swing.JButton btAboutUS;
    private javax.swing.JButton btLogin1;
    private javax.swing.JButton bthelp1;
    private javax.swing.JButton bthome1;
    private javax.swing.JButton btpencarian1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
